### ISSUE TITLE
keep_sequences() issue

### ISSUE THREAD

**Issue by wrightaprilm** [jeetsukumaran/DendroPy#101]
Hi Jeet, 

I was having an issue with the `keep_sequences()` function. 

```python
#read in dataset from phylip
ds = dendropy.DnaCharacterMatrix.get_from_path(src="plethodon.phy", schema="phylip")
#just two taxa on the tree
t_l = ds.taxon_namespace[0:5]
#make an iterator, per function docs
ds.keep_sequences(t_l)

RuntimeError: dictionary changed size during iteration
``` 
I think this is due to a python 2 --> 3 change with the dictionary keys() method now returning an iterator. There are several ways to solve this issue - making a static list of the keys in the original dictionary at the function start is one way. Another might be to add a class attribute to the character matrix objects that is the original taxon set. That may be more expedient if you anticipate other functions will have this issue.

I'm happy to contribute a fix if you let me know what would be best.

Edit: Fixed creation of list.

**Comment by jeetsukumaran** [comment]
Thanks, April. You nailed the problem and solution exactly. I'm ironing out some glitches in DendroPy in preparation for a release, so I just worked in the fix here 504b5d7d . Appreciate the heads up.

**Comment by wrightaprilm** [comment]
This might be an issue in a few other places - discard_sequences(), for example.

**Comment by jeetsukumaran** [comment]
Ok, actually it looks like ``keep_sequences`` is the only place where we are iterating over a view of a container and mutating the same container in-place in the loop. In other places such as ``discard_sequences``, we are iterating over an independent container. I'm closing this now, but please feel free to re-open and comment if you come across anything I've missed in this regard. Once again, thanks.
