### ISSUE TITLE
Missing space in DIMENSIONS command when writing DataSet to simple NEXUS format

### ISSUE THREAD

**Issue by jmenglund** [jeetsukumaran/DendroPy#105]
Hello!

When writing a DataSet to the NEXUS format using `simple=True`, there is a missing space  between "DIMENSIONS" and "NTAX".

### Test case

    >>> dendropy.__version__
    '4.4.0'
    >>> data = """
    #NEXUS

    BEGIN DATA;
        DIMENSIONS NTAX=4 NCHAR=5;
        FORMAT DATATYPE=DNA GAP=- MISSING=? MATCHCHAR=.;
        MATRIX
            t1    TCTTA
            t2    TCTTG
            t3    TCCTG
            t4    TCTTG
        ;
    END;
    """
    >>> ds = dendropy.DataSet.get_from_string(data, schema='nexus')
    >>> print(ds.as_string(schema='nexus', simple=True))
    #NEXUS

    BEGIN DATA;
        DIMENSIONSNTAX=4 NCHAR=5;
        FORMAT DATATYPE=DNA GAP=- MISSING=? MATCHCHAR=.;
        MATRIX
            t1    TCTTA
            t2    TCTTG
            t3    TCCTG
            t4    TCTTG
        ;
    END;

### Expected

    >>> print(ds.as_string(schema='nexus', simple=True))
    #NEXUS

    BEGIN DATA;
        DIMENSIONS NTAX=4 NCHAR=5;
        FORMAT DATATYPE=DNA GAP=- MISSING=? MATCHCHAR=.;
        MATRIX
            t1    TCTTA
            t2    TCTTG
            t3    TCCTG
            t4    TCTTG
        ;
    END;

Thanks!

**Comment by jeetsukumaran** [comment]
Thanks. Fixed in 083a5fff .
