### ISSUE TITLE
Bipartition comparison depends on rootedness

### ISSUE THREAD

**Issue by benjaminwilson** [jeetsukumaran/DendroPy#109]
Comparing a rooted Tree to an unrooted copy of itself gives a non-zero Robinson-Foulds distance:

```python
from dendropy.datamodel.treemodel import Tree
from dendropy.calculate.treecompare import symmetric_difference

src = '[&R] (T1:0.86,(T2:0.14,(((T4:0.38,T6:0.38):0.04,T3:0.04):0.15,T5:0.19):0.64):0.16):1.06;'
tree = Tree.get_from_string(src=src, schema='newick')

# make a copy of the Tree, then remove its root
unrooted_tree = Tree(tree)
unrooted_tree.deroot()

print(symmetric_difference(tree, unrooted_tree, is_bipartitions_updated=False))  # should be 0, but is 3
```

**Comment by jeetsukumaran** [comment]
There are splits on the rooted tree that are not present on the unrooted version. How should these be counted? 

I'm actually not sure if a symmetric difference between unrooted and rooted trees should be allowed ...

**Comment by benjaminwilson** [comment]
Shouldn't it rather be a question of whether the a bipartition of the leaf nodes is present or not (and not of its multiplicity?)  If so, it shouldn't matter whether the tree is rooted or not.

**Comment by jeetsukumaran** [comment]
Not sure I understand. There are bipartitions on the rooted tree that are simply not present on the rooted tree. It's not a multiplicity thing. I think what you are referring to is split compatibility. And sure, the extra splits on the rooted tree are compatible with the unrooted tree. But that's a different concept (but one also supported by DendroPy).

**Comment by benjaminwilson** [comment]
I must be confused about something!  Thanks for your patience.  I am had thought that splits were disjunctions of the set of taxa labels (not distinguished by the order of the subsets, so A|BCD is the same as BCD|A).  So since both trees have the same taxa labels, the symmetric difference should be defined?  I am new to the terminology, however, and probably need to go and read a textbook more closely.

So is it expected that:

```python3
def print_bipartitions(tree):
    for bp in tree.encode_bipartitions():
        print(bp.split_as_newick_string(tree.taxon_namespace))
        
print_bipartitions(tree)
```

yields:

```
((T1), (T2, T4, T6, T3, T5));
...
((T2, T4, T6, T3, T5), (T1));
(T1,T2,T4,T6,T3,T5);
```

I would have expected the 1st and the 2nd-last to be identified?

In any case, it sounds like the misunderstanding is mine.  Thanks for your help!

**Comment by jeetsukumaran** [comment]
> I must be confused about something!

Oh, it could easily be me here confused as well.

> I am had thought that splits were disjunctions of the set of taxa labels (not distinguished by the order of the subsets, so A|BCD is the same as BCD|A). 

This is correct

> So since both trees have the same taxa labels, the symmetric difference should be defined? 

This I am not sure of. 

IMHO rooted trees are basically a different model of lineages than unrooted ones. They share features, and some of these features can be compared validly. Others can be compared but require some assumptions or conventions. In the cases that these assumptions/conventions are not standardized/universal, I would say that they are undefined. That is not to say that the comparisons cannot be done, or the assumptions under which they can be done are intuitive or can be justified. But they are undefined in the sense that one persons intuition/justification for a particular application may not be the same as the others, and there is not reference to establish the objective universal rule. My thinking is that symmetric differences between splits on rooted vs unrooted trees falls in this category.

> ```
> ((T1), (T2, T4, T6, T3, T5));
> ...
> ((T2, T4, T6, T3, T5), (T1));
> (T1,T2,T4,T6,T3,T5);
> ```
> I would have expected the 1st and the 2nd-last to be identified?

It would ... in an unrooted tree. In a rooted tree, we are dealing with *leafset* partitions, not splits (Some more information can be found here: https://dendropy.org/primer/bipartitions.html). Repeat the above with an unrooted trees and the above goes away.

> In any case, it sounds like the misunderstanding is mine. Thanks for your help!
> I am new to the terminology, however, and probably need to go and read a textbook more closely.

I am open to being corrected. If you *do* find a reference that discusses the proper approach to RF distances between rooted and unrooted trees, I would love to know about it and maybe actually update the code to reflect this. I am closing this issue now, but you have an open invitation to re-open it and discuss this further if you come across anything and so we can all learn from it.
