### ISSUE TITLE
trprobs memory crash causes truncated consensus tree

### ISSUE THREAD

**Issue by willgearty** [jeetsukumaran/DendroPy#11]
I was trying to get all of the tree probabilities (using the --trprobs command), however my runs have been crashing while writing the tree probability file.
Even more problematic, it seems to forget to write the entire con tree file before moving onto the tree probabilities file (it just gets cut off without finishing the printing of the file).
Does the trprobs command require much more memory than the normal analysis?
Even if that is true, why would it stop printing the con tree before it has finished?
Does it move onto the tree probabilities while it is printing the tree, so it crashes before printing?
I have tried running the analysis without --trprobs and it runs without a problem.

**Comment by mmore500** [comment]
Closing this based on age. Feel free to re-open if this is still a concern.
