### ISSUE TITLE
TaxonNamespace partition() not working

### ISSUE THREAD

**Issue by sojovictor** [jeetsukumaran/DendroPy#113]
Hi there!

I am trying to define partitions for the taxa in a tree, but both with my own data, and when following the example in the DendroPy Primer (https://dendropy.org/primer/taxa_partitions.html), the system fails with:
AttributeError: 'TaxonNamespace' object has no attribute 'partition'

I have DendroPy 4.4.0. I would welcome any sugestions!

**Comment by davidfbibby** [comment]
I am having exactly the same problem!

**Comment by jeetsukumaran** [comment]
Looks like support for ``TaxonNamespace.partition()`` got dropped somewhere down the line. No idea why. It has been restored for now in the latest revision: 97d27f94 .

There is an example file to run this `docs/source/examples/taxon_namespace_partition.py/taxon_namespace_partition.py`.

**Comment by davidfbibby** [comment]
Thanks. Will it be restored in the main distro?

Dave

**Comment by jeetsukumaran** [comment]
In the next merge, yes.
