### ISSUE TITLE
Bipartition.edge

### ISSUE THREAD

**Issue by jtfield** [jeetsukumaran/DendroPy#123]
Hello!

i am attempting to gather information from bipartitions in trees and it would be handy to get edge information. However, i received this error:

`AttributeError: 'Bipartition' object has no attribute 'edge'`

Since this is specified as an option in the wiki I figured I'd ask whats happening here.
Thanks in advance.

**Comment by jeetsukumaran** [comment]
Could you post a basic code example?

**Comment by jtfield** [comment]
Yup! sorry, I was moments from doing so.

`taxa = dendropy.TaxonNamespace()
    mle = dendropy.Tree.get(path=args.tree_file, schema='newick', taxon_namespace=taxa)
    for split in mle.bipartition_encoding:
        print(split.edge)`

The tree file is a generic newick tree. I can recreate a string example if that helps.

**Comment by jeetsukumaran** [comment]
Could you point out the place in the documentation where this is shown as the way to dereference the edge? This has to be fixed. 

The correct way to dereference the edge is:

~~~
print(mle.bipartition_edge_map[split])
~~~

**Comment by jtfield** [comment]
Here is the page[here](https://dendropy.org/primer/bipartitions.html) 
I don't know how to point to a particular position on the page but its in the: 
2nd paragraph of the Bipartition Encoding section

Thanks very much!

**Comment by jeetsukumaran** [comment]
Thanks. I will update the document to reflect the current API. Hope the above works for you in the mean time.
