### ISSUE TITLE
Please tag a new release that contains 972d12fe2be3241c33fb2a969e5f0271158a24fc

### ISSUE THREAD

**Issue by jonchang** [jeetsukumaran/DendroPy#125]
```
python3.8/site-packages/dendropy/utility/container.py:357: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    class CaseInsensitiveDict(collections.MutableMapping):
```

Python 3.9 will be released in October of this year. To ensure that DendroPy continues to work I'd prefer that a new version of DendroPy that contains this commit is tagged and released on PyPI. Even a patch release that contains only the cherry-pick of 972d12fe2be3241c33fb2a969e5f0271158a24fc would be sufficient to avoid breaking old code. Thanks!

**Comment by jeetsukumaran** [comment]
I'd be happy to tag formal release. No idea that it was so long since the last one.

Only catch is, it's going to take me a while to compose a meaningful change log. I might wimp out and just refer folks to the Git log. 

One thing to consider as a workaround in the future, if ``main`` is too stale, is to latch on to the ``development-main`` branch. Things there are _usually_ stable enough, with most "WIP" stuff on side branches.You can bake this requirement into your project by specifying the following in your ``setup.py``:

```Python
setup(
    install_requires=[
         .
         .
        "DendroPy @ git+https://github.com:jeetsukumaran/DendroPy.git@development-master#egg=DendroPy",
         .
         .
        ],
)
```

For e.g.,

```
setup(
    name=__project__,
    version=__version__,
    author="Bilbo Baggins and Frodo Baggins",
    author_email="bilbo@rivendell.com and frodo@shire.com",
    packages=find_packages("src"),
    package_dir={"": "src"},
    scripts=[
        "bin/foo,
        ],
    test_suite = "tests",
    url="https://github.com/hobbitlogic/delineate/",
    license="LICENSE.txt",
    description="There and Back Again.",
    long_description=_read(["README.txt"]),
    install_requires=[
        "numpy>=1.18.1",
        "scipy>=1.4.1",
        "DendroPy @ git+https://github.com:jeetsukumaran/DendroPy.git@development-master#egg=DendroPy",
        ]
)
```

Local install invocation is:

```
 python3 -m pip install --upgrade git+git://github.com/jeetsukumaran/DendroPy.git@development-master
```

**Comment by jeetsukumaran** [comment]
p.s. In case tagging a new release slips off my event horizon, please remind me as the time looms!

**Comment by jonchang** [comment]
Thanks Jeet! I'd probably just point it to my own fork with with the patch applied, but this info is handy regardless! I'll be sure to remind you if the 3.9 deadline gets uncomfortably close.

**Comment by jonchang** [comment]
@jeetsukumaran Python 3.9 is now out.

**Comment by jeetsukumaran** [comment]
Thanks for the reminder. I pushed a release. Need to work up a change description / announcement.

**Comment by jonchang** [comment]
Thanks!!
