### ISSUE TITLE
Re-enable secure SSL in setup.py

### ISSUE THREAD

**Issue by kislyuk** [jeetsukumaran/DendroPy#133]
Hi, I noticed that DendroPy disables SSL certificate verification globally in setup.py:
```
import ssl
if hasattr(ssl, '_create_unverified_context'):
    ssl._create_default_https_context = ssl._create_unverified_context
```
It seems this workaround should no longer be necessary. Can it be removed to avoid any doubts about security at install time?

**Comment by jeetsukumaran** [comment]
No longer necessary universally, or no longer necessary for particular/latest versions of Python, OS, etc.?

**Comment by kislyuk** [comment]
Disabling SSL security is not necessary in any supported configuration of Python or its host OS that I'm aware of.

**Comment by mmore500** [comment]
This ssl code in question been removed from `setup.py`
