### ISSUE TITLE
Typo in PhylogeneticIndependentContrasts class

### ISSUE THREAD

**Issue by Puumanamana** [jeetsukumaran/DendroPy#134]
Hi,

I've been trying to import the `PhylogeneticIndependentContrasts` class from `dendropy` by following the tutorial at https://dendropy.readthedocs.io/en/v3.12.1/tutorial/phylogenetic_character_analyses.html. However, I could not import it with:
`from dendropy.model.continuous import PhylogeneticIndependentContrasts`

However, it worked with (notice the additional **s** in contrasts):
`from dendropy.model.continuous import PhylogeneticIndependentConstrasts`

The typo seems to be present in the source code here:
https://github.com/jeetsukumaran/DendroPy/blob/main/src/dendropy/model/continuous.py

**Comment by jeetsukumaran** [comment]
Thanks for pointing this out! Fixed it in 5d98812f
