### ISSUE TITLE
Documentation appears to be down

### ISSUE THREAD

**Issue by ericmjl** [jeetsukumaran/DendroPy#140]
I attempted to access dendropy.org today, but was directed to the following website instead:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2631566/157122678-f78cfa43-b3f5-4822-952a-7d26b45be680.png">

It appears the domain name is no longer registered.

Would you be open to publishing the docs on GitHub Pages instead? I'm happy to try to help in some capacity here.

**Comment by chrysn** [comment]
The issue is resolved, documentation is showing fine right now.

**Comment by ericmjl** [comment]
Thank you!
