### ISSUE TITLE
Underscores appear to be removed in tree taxonnamespace

### ISSUE THREAD

**Issue by Mahim1997** [jeetsukumaran/DendroPy#146]
I have used the following codeblock to read a tree that has underscores.

``` python

import dendropy

def read_tree(inputStreeFile):
    taxa = dendropy.TaxonNamespace()
    tree = dendropy.Tree.get_from_path(inputStreeFile, "newick", taxon_namespace=taxa, rooting="force-rooted")
    return tree

tree = read_tree(inputStreeFile) # Required input file
treeStr = tree.as_string("newick").strip()

# Debug print
print(treeStr)
print(tree.taxon_namespace)
```

The tree is something like this:
`
((checking_first,checking_second),(checking_third,checking_fourth));
`

The tree's taxon namespace is something like this:
`
['checking first', 'checking second', 'checking third', 'checking fourth']
`

The underscores appear to be missing. If it is by design choice, I guess it could be highlighted in the function's docs.

**Comment by jeetsukumaran** [comment]
I guess you have not actually read the full library documentation, or, for that matter, the actual Newick specifications.
