### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by WSDeWitt** [jeetsukumaran/DendroPy#150]
I'd like to access the dendropy documentation, but the homepage domain http://dendropy.org is not active. Has it moved somewhere else?

<img width="600" alt="image" src="https://user-images.githubusercontent.com/1173298/222933278-a5718522-cb6a-46f1-9ee4-1ac18bf26c83.png">

**Comment by mmore500** [comment]
Looks like <dendropy.org> is back up. If this happens again in the future, the documentation can also be accessed at <https://dendropy.readthedocs.io/en/main/>.
