### ISSUE TITLE
Website dendropy.org is down

### ISSUE THREAD

**Issue by Wytamma** [jeetsukumaran/DendroPy#185]
It seems like the https://dendropy.org website resolves to a news site instead of the docs?

I found a v4.4.0 version of the docs -> https://dendropy.readthedocs.io/en/main. Is there a newer version of the website hosted somewhere?

**Comment by mmore500** [comment]
Thanks for the tip on this. I’ve updated the links in the README and will follow up shortly when we get the read the docs up to date.

**Comment by mmore500** [comment]
@jeetsukumaran when you have a chance, can you click through here to enable GitHub pages for the repository? https://github.com/jeetsukumaran/DendroPy/settings/pages

That’ll be the easiest way to get the docs back up to date.

**Comment by mmore500** [comment]
Hi! Was able to get a fully up to date version of the docs out at 

> https://jeetsukumaran.github.io/DendroPy/

I will follow up to close this issue soon once I update the repository with this info.

**Comment by Wytamma** [comment]
Thanks @mmore500! You’re a champion

**Comment by mmore500** [comment]
Thanks @Wytamma ❤️
