### ISSUE TITLE
Change of consensus frequency in sumtrees.py does not work

### ISSUE THREAD

**Issue by tiagoantao** [jeetsukumaran/DendroPy#24]
The -f parameter has no effect. Suggested change:
tree = tree_array.consensus_tree(min_consensus_freq=args.min_consensus_freq, summarize_splits=False)

Becomes

tree = tree_array.consensus_tree(min_freq=args.min_consensus_freq, summarize_splits=False)

Either that or change treedatamodel.py

**Comment by jeetsukumaran** [comment]
Thanks. This has been fixed in revision 5a32a69, and will be in the next release.
