### ISSUE TITLE
leafset_taxa() missing "index" kwarg

### ISSUE THREAD

**Issue by daveuu** [jeetsukumaran/DendroPy#28]
It seems [leafset_taxa()](https://github.com/jeetsukumaran/DendroPy/blob/6b48491a5522edc77ebe2c477a48dcff11240662/dendropy/datamodel/treemodel.py#L681) is missing "index" as a key word argument causing a NameError?

**Comment by jeetsukumaran** [comment]
Thanks. Fixed in cd09927.

On 8/21/15 2:38 PM, daveuu wrote:
> It seems leafset_taxa()
> <https://github.com/jeetsukumaran/DendroPy/blob/6b48491a5522edc77ebe2c477a48dcff11240662/dendropy/datamodel/treemodel.py#L681>
> is missing "index" as a key word argument causing a NameError?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeetsukumaran/DendroPy/issues/28>.
>

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------

**Comment by daveuu** [comment]
I was trying to test the change by doing the following, but I don't think I'm doing things correctly because the typos remain. I'm new to git . . . does the below code seem like a reasonable/correct workflow?

```
mkdir ~/dendropy_test
cd ~/dendropy_test
git clone https://github.com/jeetsukumaran/DendroPy
cd DendroPy
git checkout -b  development-master
cd ..
ipython2
import sys,os
sys.path.insert(0,os.path.sep.join([os.path.abspath(os.path.curdir),'DendroPy']))
import dendropy
print(dendropy.__file__)
~/dendropy_test/DendroPy/dendropy/__init__.pyc
tree = dendropy.Tree.get_from_string('((A,B),(C,D));', 'newick', rooting=None)
tree.encode_bipartitions()
tree.bipartition_encoding[0].leafset_taxa(tree.taxon_namespace)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
```
etc.

**Comment by jeetsukumaran** [comment]
You probably want to clone the repository and install the project in 
developer mode. This is discussed with examples in the documentation:

	http://dendropy.org/downloading.html#cloning-the-source-code-repository

You should probably make sure that you uninstall any current 
installation of DendroPy before you do so.

-- jeet

On 8/29/15 7:41 PM, daveuu wrote:
> I was trying to test the change by doing the following, but I don't
> think I'm doing things correctly because the typos remain. I'm new to
> git . . . does the below code seem like a reasonable/correct workflow?
>
> |mkdir ~/dendropy_test cd ~/dendropy_test git clone
> https://github.com/jeetsukumaran/DendroPy cd DendroPy git checkout -b
> development-master cd .. ipython2 import sys,os
> sys.path.insert(0,os.path.sep.join([os.path.abspath(os.path.curdir),'DendroPy']))
> import dendropy print(dendropy.__file__)
> ~/dendropy_test/DendroPy/dendropy/__init__.pyc tree =
> dendropy.Tree.get_from_string('((A,B),(C,D));', 'newick', rooting=None)
> tree.encode_bipartitions()
> tree.bipartition_encoding[0].leafset_taxa(tree.taxon_namespace)
> ---------------------------------------------------------------------------
> NameError Traceback (most recent call last) |
>
> etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeetsukumaran/DendroPy/issues/28#issuecomment-136062892>.
>

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------
