### ISSUE TITLE
PatristicDistanceMatrix

### ISSUE THREAD

**Issue by basic99** [jeetsukumaran/DendroPy#45]
Hi,

I have a script that uses PatristicDistanceMatrix. I found it does not work on 4.1 and I looked and it says legacy: will soon be deprecated. I tried using patristic_distance but since I use the whole tree this was much slower. 

Jim

**Comment by jeetsukumaran** [comment]
As the deprecation message should have indicated, you can use the ``PhylogeneticDistanceMatrix`` instead:  http://dendropy.org/primer/phylogenetic_distances.html

**Comment by basic99** [comment]
Thanks. That works.

On 03/21/2016 04:43 PM, Jeet Sukumaran wrote:
>
> As the deprecation message should have indicated, you can use the 
> |PhylogeneticDistanceMatrix| instead: 
> http://dendropy.org/primer/phylogenetic_distances.html
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/jeetsukumaran/DendroPy/issues/45#issuecomment-199471903>
>


-- 
James B. White
Cary, NC
919-380-9615
http://whitecodingandmaps.com
