### ISSUE TITLE
sumtrees.py outputs an extra tree when onto a target tree

### ISSUE THREAD

**Issue by mossmatters** [jeetsukumaran/DendroPy#47]
Given the command:

`sumtrees.py bootstrap.trees -f 0.33 -F newick --suppress-annotations -o output.tree -i newick`

sumtrees will output a single line containing a tree, as expected. However, if a (single) target tree is specified:

`sumtrees.py bootstrap.trees -f 0.33 -F newick --suppress-annotations -o output.tree -i newick -t target.tree`

The output contains two identical trees. I'm using version 4.1.0 of both Dendropy and SumTrees, on Python 2.7.3

Perhaps the culprit is line 1720:

`target_trees.append(tree)`

Which occurs immediately after a message about number of target trees is printed, and is outside the if/else block regarding target trees, and outside the for loop iterating over the target trees. 

Indeed, if I add a second target tree to the target.tree file, SumTrees prints:

`SumTrees: Summarizing onto 2 target trees defined in 'target.tree':`

but then it outputs three trees.

**Comment by jeetsukumaran** [comment]
Hi Matt,

Thanks for pointing this issue AND its solution out!

I've (hopefully) fixed it in on the ``development-master`` branch HEAD: 376fe2f .

Let me know if it works, or if you encounter any other issues.
