### ISSUE TITLE
python3 test failure

### ISSUE THREAD

**Issue by wwood** [jeetsukumaran/DendroPy#48]
Hi,

I'm attempting to package dendropy for the GNU Guix package manager, and I'm hitting 2 errors when running the tests of python3(.4.3). I've not done very extensive searching, but I wonder if these have already been fixed in master and are unreleased? Or is there some other issue? There is no problem on python 2.7.
```
======================================================================
ERROR: test_distances (dendropy.test.test_phylogenetic_distance_matrix.NodeToNodeDistancesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/test/test_phylogenetic_distance_matrix.py", line 817, in test_distances
    ndm = tree.node_distance_matrix()
  File "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/datamodel/treemodel.py", line 5512, in node_distance_matrix
    return NodeDistanceMatrix.from_tree(tree=self)
  File "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/calculate/phylogeneticdistance.py", line 1363, in from_tree
    ndm.compile_from_tree(tree=tree)
  File "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/calculate/phylogeneticdistance.py", line 1393, in compile_from_tree
    for ch1_subtree_node in self._node_phylogenetic_distances[ch1].keys():
RuntimeError: dictionary changed size during iteration

======================================================================
ERROR: test_mrca (dendropy.test.test_phylogenetic_distance_matrix.NodeToNodeDistancesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/test/test_phylogenetic_distance_matrix.py", line 839, in test_mrca
    ndm = tree.node_distance_matrix()
  File "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/datamodel/treemodel.py", line 5512, in node_distance_matrix
    return NodeDistanceMatrix.from_tree(tree=self)
  File "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/calculate/phylogeneticdistance.py", line 1363, in from_tree
    ndm.compile_from_tree(tree=tree)
  File "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/calculate/phylogeneticdistance.py", line 1393, in compile_from_tree
    for ch1_subtree_node in self._node_phylogenetic_distances[ch1].keys():
RuntimeError: dictionary changed size during iteration

----------------------------------------------------------------------
Ran 833 tests in 467.171s

FAILED (errors=2)
```
Thanks,
ben

**Comment by jeetsukumaran** [comment]
Hi Ben,

Hmmm.

I have both those tests passing under 3.5 on both the current master 
(which is 4.1.0; revision=715b4cc) as well as the development-master HEAD:

~~~
[venv:python-3.5.0][dendropy:master:715b4cc]$ p -m 
dendropy.test.test_phylogenetic_distance_matrix NodeToNodeDistancesTest
..
----------------------------------------------------------------------
Ran 2 tests in 8.639s

OK

[venv:python-3.5.0][dendropy:master:715b4cc]$ git checkout 
development-master
Switched to branch 'development-master'

[venv:python-3.5.0][dendropy:development-master:d49b3db]$ p -m 
dendropy.test.test_phylogenetic_distance_matrix NodeToNodeDistancesTest
..
----------------------------------------------------------------------
Ran 2 tests in 8.434s

OK
~~~



On 4/22/16 11:24 PM, Ben J Woodcroft wrote:
> Hi,
>
> I'm attempting to package dendropy for the GNU Guix package manager, and
> I'm hitting 2 errors when running the tests of python3(.4.3). I've not
> done very extensive searching, but I wonder if these have already been
> fixed in master and are unreleased? Or is there some other issue? There
> is no problem on python 2.7.
>
> |======================================================================
> ERROR: test_distances
> (dendropy.test.test_phylogenetic_distance_matrix.NodeToNodeDistancesTest) ----------------------------------------------------------------------
> Traceback (most recent call last): File
> "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/test/test_phylogenetic_distance_matrix.py",
> line 817, in test_distances ndm = tree.node_distance_matrix() File
> "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/datamodel/treemodel.py",
> line 5512, in node_distance_matrix return
> NodeDistanceMatrix.from_tree(tree=self) File
> "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/calculate/phylogeneticdistance.py",
> line 1363, in from_tree ndm.compile_from_tree(tree=tree) File
> "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/calculate/phylogeneticdistance.py",
> line 1393, in compile_from_tree for ch1_subtree_node in
> self._node_phylogenetic_distances[ch1].keys(): RuntimeError: dictionary
> changed size during iteration
> ======================================================================
> ERROR: test_mrca
> (dendropy.test.test_phylogenetic_distance_matrix.NodeToNodeDistancesTest) ----------------------------------------------------------------------
> Traceback (most recent call last): File
> "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/test/test_phylogenetic_distance_matrix.py",
> line 839, in test_mrca ndm = tree.node_distance_matrix() File
> "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/datamodel/treemodel.py",
> line 5512, in node_distance_matrix return
> NodeDistanceMatrix.from_tree(tree=self) File
> "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/calculate/phylogeneticdistance.py",
> line 1363, in from_tree ndm.compile_from_tree(tree=tree) File
> "/tmp/nix-build-python-dendropy-4.1.0.drv-0/DendroPy-4.1.0/dendropy/calculate/phylogeneticdistance.py",
> line 1393, in compile_from_tree for ch1_subtree_node in
> self._node_phylogenetic_distances[ch1].keys(): RuntimeError: dictionary
> changed size during iteration
> ----------------------------------------------------------------------
> Ran 833 tests in 467.171s FAILED (errors=2) |
>
> Thanks,
> ben
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jeetsukumaran/DendroPy/issues/48>
>

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------

**Comment by wwood** [comment]
Thanks for the quick response. Looks like it is due to the python version difference or a change made in master after the last release (4.1.0). I'll investigate further but either way we can close this issue I think.

**Comment by jeetsukumaran** [comment]
Ok. Feel free to re-open if it is an issue with library. FYI, 715b4cc/master is what's been tagged as 4.1.0.

**Comment by wwood** [comment]
Hmm. I still have not been able to figure out what is happening here. However, I have been able to reproduce this outside Guix, in Ubuntu:
```
ben@u:~/git/DendroPy$ PYTHONPATH= python3 -m dendropy.test.test_phylogenetic_distance_matrix NodeToNodeDistancesTest
/home/ben/git/DendroPy/dendropy/dataio/newickreader.py:314: PendingDeprecationWarning: generator 'NewickReader.tree_iter' raised StopIteration
  tree_factory=tree_factory):
EE
======================================================================
ERROR: test_distances (__main__.NodeToNodeDistancesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/git/DendroPy/dendropy/test/test_phylogenetic_distance_matrix.py", line 817, in test_distances
    ndm = tree.node_distance_matrix()
  File "/home/ben/git/DendroPy/dendropy/datamodel/treemodel.py", line 5512, in node_distance_matrix
    return NodeDistanceMatrix.from_tree(tree=self)
  File "/home/ben/git/DendroPy/dendropy/calculate/phylogeneticdistance.py", line 1363, in from_tree
    ndm.compile_from_tree(tree=tree)
  File "/home/ben/git/DendroPy/dendropy/calculate/phylogeneticdistance.py", line 1393, in compile_from_tree
    for ch1_subtree_node in self._node_phylogenetic_distances[ch1].keys():
RuntimeError: dictionary changed size during iteration

======================================================================
ERROR: test_mrca (__main__.NodeToNodeDistancesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ben/git/DendroPy/dendropy/test/test_phylogenetic_distance_matrix.py", line 839, in test_mrca
    ndm = tree.node_distance_matrix()
  File "/home/ben/git/DendroPy/dendropy/datamodel/treemodel.py", line 5512, in node_distance_matrix
    return NodeDistanceMatrix.from_tree(tree=self)
  File "/home/ben/git/DendroPy/dendropy/calculate/phylogeneticdistance.py", line 1363, in from_tree
    ndm.compile_from_tree(tree=tree)
  File "/home/ben/git/DendroPy/dendropy/calculate/phylogeneticdistance.py", line 1393, in compile_from_tree
    for ch1_subtree_node in self._node_phylogenetic_distances[ch1].keys():
RuntimeError: dictionary changed size during iteration

----------------------------------------------------------------------
Ran 2 tests in 0.036s

FAILED (errors=2)
```
I note the extra warning at the top which I did not report before. However, I see the same warning  when running the same test on development-master, so presumably it isn't helpful.

Since I'm not observing this in development-master I'll just disable these tests in my Guix patch, and not reopen this.

Thanks,
ben
