### ISSUE TITLE
Probelms with DendroPy compiled with other software.

### ISSUE THREAD

**Issue by Lily-WL** [jeetsukumaran/DendroPy#50]
Thank you for your platform to support the use of DendroPy.

I installed a software called CheckM . And DendroPy was also installed. But seems there are some errors. The details are as follows:

**[root@student ~]# python -m dendropy**
DendroPy version      : DendroPy 4.1.0
DendroPy location     : /usr/local/lib/python2.7/site-packages/dendropy
Python version        : 2.7 (r27:82500, Apr 29 2016, 10:17:23) [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)]
Python executable     : /usr/local/bin/python
Python site packages  : ['/usr/local/lib/python2.7/site-packages', '/usr/local/lib/site-python']
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x1ed8490: '1'>), ('0', <StateIdentity at 0x1ed84d0: '0'>)])> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x1ed8490: '1'>), ('0', <StateIdentity at 0x1ed84d0: '0'>)])> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([(0, <StateIdentity at 0x1ed8490: '1'>), (1, <StateIdentity at 0x1ed84d0: '0'>)])> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored

**Comment by jeetsukumaran** [comment]
Hi, 

This is a tricky one. I cannot replicate the error, and I am not sure what might be going on to cause this on your end. Best thing I can suggest is to try a clean install of DendroPy:

    $ pip install --upgrade dendropy

**Comment by Lily-WL** [comment]
### Dear Sir,

Thank you for your reply.

### New installation is successful. As the discription:
_Installing collected packages: setuptools
  Found existing installation: setuptools 20.10.1
    Uninstalling setuptools-20.10.1:
      Successfully uninstalled setuptools-20.10.1
Successfully installed setuptools-21.0.0_

### However, it seems the error still exit. IS it the matter with FrozenOrderedDict?
**_[root@student ~]# python -m dendropy**
DendroPy version      : DendroPy 4.1.0
DendroPy location     : /usr/local/lib/python2.7/site-packages/dendropy
Python version        : 2.7 (r27:82500, Apr 29 2016, 10:17:23) [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)]
Python executable     : /usr/local/bin/python
Python site packages  : ['/usr/local/lib/python2.7/site-packages', '/usr/local/lib/site-python']
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x21a74d0: '1'>), ('0', <StateIdentity at 0x21a7510: '0'>)])> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x21a74d0: '1'>), ('0', <StateIdentity at 0x21a7510: '0'>)])> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([(0, <StateIdentity at 0x21a74d0: '1'>), (1, <StateIdentity at 0x21a7510: '0'>)])> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored_

**Comment by jeetsukumaran** [comment]
It is, but I cannot tell from what you have give here what the issue is.

Have you tried running the tests:

    $ python setup.py test

**Comment by jeetsukumaran** [comment]
Can also try using the verbose ("-v") flag: ``python -vm dendropy``.

**Comment by jeetsukumaran** [comment]
Googling the message it appears possible (by no means certain) that the issue might be related garbage collection on exiting the program:

https://answers.atlassian.com/questions/24661360/exception-on-exit-after-upgrading-to-python2.7.10
https://groups.google.com/forum/#!topic/theano-users/U6PEg-i-Qu4
http://stackoverflow.com/questions/18163697/exception-typeerror-warning-sometimes-shown-sometimes-not-when-using-throw-meth

Except that we only use __del__ in a couple of places, not related to this code.

**Comment by Lily-WL** [comment]
### Dear sir，

 Thank you for your immediatedly reply.

 I executed "**python -vm dendropy**". Seen from the feedback, it seems the error came from the **_dendropy.datamodel_**.charstatemodel. As follows. 

.................
_cleanup[2] dendropy.datamodel.charstatemodel
_Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x151d4d0: '1'>), ('0', <StateIdentity at 0x151d510: '0'>)])> ignored_
_Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x151d4d0: '1'>), ('0', <StateIdentity at 0x151d510: '0'>)])> ignored_
_Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored
_Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([(0, <StateIdentity at 0x151d4d0: '1'>), (1, <StateIdentity at 0x151d510: '0'>)])> ignored_
_Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored_

**Comment by Lily-WL** [comment]
### Furthermore, I executed "python setup.py test" and fail.

**[root@student DendroPy-4.0.3]# python setup.py test**
......................
======================================================================
ERROR: test_copy (dendropy.test.test_container_frozen_ordered_dict.FrozenOrderedDictTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/DendroPy-4.0.3/dendropy/test/test_container_frozen_ordered_dict.py", line 79, in test_copy
    d2 = copy.copy(self.d)
  File "/usr/local/lib/python2.7/copy.py", line 80, in copy
    return copier(x)
  File "/opt/DendroPy-4.0.3/dendropy/utility/container.py", line 672, in __copy__
    temp = FrozenOrderedDict()
  File "/opt/DendroPy-4.0.3/dendropy/utility/container.py", line 613, in __init__
    super(FrozenOrderedDict, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/collections.py", line 48, in __init__
    self.update(*args, **kwds)
TypeError: update() takes exactly 2 arguments (1 given)

======================================================================
ERROR: test_deepcopy (dendropy.test.test_container_frozen_ordered_dict.FrozenOrderedDictTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/DendroPy-4.0.3/dendropy/test/test_container_frozen_ordered_dict.py", line 70, in test_deepcopy
    d2 = copy.deepcopy(self.d)
  File "/usr/local/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/opt/DendroPy-4.0.3/dendropy/utility/container.py", line 659, in __deepcopy__
    temp = FrozenOrderedDict()
  File "/opt/DendroPy-4.0.3/dendropy/utility/container.py", line 613, in __init__
    super(FrozenOrderedDict, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/collections.py", line 48, in __init__
    self.update(*args, **kwds)
TypeError: update() takes exactly 2 arguments (1 given)

======================================================================
ERROR: runTest (dendropy.test.test_container_normalized_bitmask_dict.TestNormalizedBitmaskDict)
Testing NormalizedBitmaskDict
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/DendroPy-4.0.3/dendropy/test/test_container_normalized_bitmask_dict.py", line 38, in runTest
    d = container.NormalizedBitmaskDict(fill_bitmask=fill_bitmask)
  File "/opt/DendroPy-4.0.3/dendropy/utility/container.py", line 258, in __init__
    collections.OrderedDict.__init__(self)
  File "/usr/local/lib/python2.7/collections.py", line 48, in __init__
    self.update(*args, **kwds)
TypeError: update() takes exactly 2 arguments (1 given)

======================================================================
FAIL: test_collection_comments_and_annotations (dendropy.test.test_dataio_nexml_reader_tree_list.NexmlStandardTreeParsingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/DendroPy-4.0.3/dendropy/test/test_dataio_nexml_reader_tree_list.py", line 60, in test_collection_comments_and_annotations
    expected_metadata)
  File "/opt/DendroPy-4.0.3/dendropy/test/support/standard_file_test_trees.py", line 127, in compare_annotations_to_json_metadata_dict
    self.assertEqual(item_annotations_as_dict, expected_metadata)
AssertionError: {'Merycoidodon_%_$_permeant': 'envyingly247994 wagonload130853 ganglioneuron4665 [truncated]... != {'$_demivotary_#_monumentlike': '31', '!_missuggestion_frondivorous_#': 'False', [truncated]...
Diff is 676 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 785 tests in 502.328s

FAILED (failures=1, errors=3)
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('a', 1), ('b', 2), ('c', 3)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('a', 1), ('b', 2), ('c', 3)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('a', 1), ('b', 2), ('c', 3)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('a', 1), ('b', 2), ('c', 3)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('a', 1), ('b', 2), ('c', 3)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('a', 1), ('b', 2), ('c', 3)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('a', 1), ('b', 2), ('c', 3)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('0', <StateIdentity at 0x3c7ae8d0: '0'>), ('1', <StateIdentity at 0x3c7ae910: '1'>), ('2', <StateIdentity at 0x3c7ae950: '2'>), ('3', <StateIdentity at 0x3c7ae990: '3'>), ('4', <StateIdentity at 0x3c7ae9d0: '4'>), ('-', <StateIdentity at 0x3c7ae890: '-'>), ('?', <StateIdentity at 0x3c7aea10: '?'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([(None, <StateIdentity at 0x3c7aea10: '?'>), ('0', <StateIdentity at 0x3c7ae8d0: '0'>), ('1', <StateIdentity at 0x3c7ae910: '1'>), ('2', <StateIdentity at 0x3c7ae950: '2'>), ('3', <StateIdentity at 0x3c7ae990: '3'>), ('4', <StateIdentity at 0x3c7ae9d0: '4'>), ('-', <StateIdentity at 0x3c7ae890: '-'>), ('?', <StateIdentity at 0x3c7aea10: '?'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([(0, <StateIdentity at 0x3c7ae8d0: '0'>), (1, <StateIdentity at 0x3c7ae910: '1'>), (2, <StateIdentity at 0x3c7ae950: '2'>), (3, <StateIdentity at 0x3c7ae990: '3'>), (4, <StateIdentity at 0x3c7ae9d0: '4'>), (5, <StateIdentity at 0x3c7ae890: '-'>), (6, <StateIdentity at 0x3c7aea10: '?'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([(frozenset([<StateIdentity at 0x3c7ae910: '1'>, <StateIdentity at 0x3c7ae890: '-'>, <StateIdentity at 0x3c7ae950: '2'>, <StateIdentity at 0x3c7ae8d0: '0'>, <StateIdentity at 0x3c7ae990: '3'>, <StateIdentity at 0x3c7ae9d0: '4'>]), <StateIdentity at 0x3c7aea10: '?'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0xdebc50: '1'>), ('0', <StateIdentity at 0xdebc90: '0'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0xdebc50: '1'>), ('0', <StateIdentity at 0xdebc90: '0'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([(0, <StateIdentity at 0xdebc50: '1'>), (1, <StateIdentity at 0xdebc90: '0'>)])> ignored
Exception dendropy.utility.container.ImmutableTypeError: ImmutableTypeError('FrozenOrderedDict is immutable',) in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored

**Comment by jeetsukumaran** [comment]
Can you replicate the problem with a minimal fragment like the following?

     python -c "from dendropy.utility.container import 
FrozenOrderedDict; q = FrozenOrderedDict()"



On 5/6/16 1:31 AM, Lily-WL wrote:
>
>       Furthermore, I executed "python setup.py test" and fail.
>
> *[root@student DendroPy-4.0.3]# python setup.py test*
>
>
>   ......................
>
>
>     ERROR: test_copy
>     (dendropy.test.test_container_frozen_ordered_dict.FrozenOrderedDictTest)
>
> Traceback (most recent call last):
> File
> "/opt/DendroPy-4.0.3/dendropy/test/test_container_frozen_ordered_dict.py",
> line 79, in test_copy
> d2 = copy.copy(self.d)
> File "/usr/local/lib/python2.7/copy.py", line 80, in copy
> return copier(x)
> File "/opt/DendroPy-4.0.3/dendropy/utility/container.py", line 672, in
> *copy*
> temp = FrozenOrderedDict()
> File "/opt/DendroPy-4.0.3/dendropy/utility/container.py", line 613, in
> *init*
> super(FrozenOrderedDict, self).*init*(/args, */kwargs)
> File "/usr/local/lib/python2.7/collections.py", line 48, in *init*
> self.update(/args, */kwds)
> TypeError: update() takes exactly 2 arguments (1 given)
>
>
>     ERROR: test_deepcopy
>     (dendropy.test.test_container_frozen_ordered_dict.FrozenOrderedDictTest)
>
> Traceback (most recent call last):
> File
> "/opt/DendroPy-4.0.3/dendropy/test/test_container_frozen_ordered_dict.py",
> line 70, in test_deepcopy
> d2 = copy.deepcopy(self.d)
> File "/usr/local/lib/python2.7/copy.py", line 174, in deepcopy
> y = copier(memo)
> File "/opt/DendroPy-4.0.3/dendropy/utility/container.py", line 659, in
> *deepcopy*
> temp = FrozenOrderedDict()
> File "/opt/DendroPy-4.0.3/dendropy/utility/container.py", line 613, in
> *init*
> super(FrozenOrderedDict, self).*init*(/args, */kwargs)
> File "/usr/local/lib/python2.7/collections.py", line 48, in *init*
> self.update(/args, */kwds)
> TypeError: update() takes exactly 2 arguments (1 given)
>
>
> ERROR: runTest
> (dendropy.test.test_container_normalized_bitmask_dict.TestNormalizedBitmaskDict)
>
>
>     Testing NormalizedBitmaskDict
>
> Traceback (most recent call last):
> File
> "/opt/DendroPy-4.0.3/dendropy/test/test_container_normalized_bitmask_dict.py",
> line 38, in runTest
> d = container.NormalizedBitmaskDict(fill_bitmask=fill_bitmask)
> File "/opt/DendroPy-4.0.3/dendropy/utility/container.py", line 258, in
> *init*
> collections.OrderedDict.*init*(self)
> File "/usr/local/lib/python2.7/collections.py", line 48, in *init*
> self.update(/args, */kwds)
> TypeError: update() takes exactly 2 arguments (1 given)
>
>
>     FAIL: test_collection_comments_and_annotations
>     (dendropy.test.test_dataio_nexml_reader_tree_list.NexmlStandardTreeParsingTestCase)
>
> Traceback (most recent call last):
> File
> "/opt/DendroPy-4.0.3/dendropy/test/test_dataio_nexml_reader_tree_list.py",
> line 60, in test_collection_comments_and_annotations
> expected_metadata)
> File
> "/opt/DendroPy-4.0.3/dendropy/test/support/standard_file_test_trees.py",
> line 127, in compare_annotations_to_json_metadata_dict
> self.assertEqual(item_annotations_as_dict, expected_metadata)
> AssertionError: {'Merycoidodon_%/$_permeant': 'envyingly247994
> wagonload130853 ganglioneuron4665 [truncated]... !=
> {'$_demivotary/#/monumentlike': '31', '!_missuggestion_frondivorous/#':
> 'False', [truncated]...
> Diff is 676 characters long. Set self.maxDiff to None to see it.
>
> ------------------------------------------------------------------------
>
> Ran 785 tests in 502.328s
>
> FAILED (failures=1, errors=3)
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ), ('1', ),
> ('2', ), ('3', ), ('4', ), ('-', ), ('?', )])> ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ), ('0', ),
> ('1', ), ('2', ), ('3', ), ('4', ), ('-', ), ('?', )])> ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ), (1, ), (2,
> ), (3, ), (4, ), (5, ), (6, )])> ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in , , , , , ]),
> )])> ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ), ('0', )])>
> ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ), ('0', )])>
> ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ), (1, )])> ignored
> Exception dendropy.utility.container.ImmutableTypeError:
> ImmutableTypeError('FrozenOrderedDict is immutable',) in ignored
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jeetsukumaran/DendroPy/issues/50#issuecomment-217351467>
>

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------

**Comment by Lily-WL** [comment]
**[root@student DendroPy-4.0.3]# python -c "from dendropy.utility.container import FrozenOrderedDict; q = FrozenOrderedDict()"**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "dendropy/utility/container.py", line 613, in __init__
    super(FrozenOrderedDict, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/collections.py", line 48, in __init__
    self.update(*args, **kwds)
TypeError: update() takes exactly 2 arguments (1 given)
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x1a96d90: '1'>), ('0', <StateIdentity at 0x1a96dd0: '0'>)])> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([('1', <StateIdentity at 0x1a96d90: '1'>), ('0', <StateIdentity at 0x1a96dd0: '0'>)])> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict([(0, <StateIdentity at 0x1a96d90: '1'>), (1, <StateIdentity at 0x1a96dd0: '0'>)])> ignored
Exception AttributeError: "'NoneType' object has no attribute 'ImmutableTypeError'" in <bound method FrozenOrderedDict.__del__ of FrozenOrderedDict()> ignored

**Comment by jeetsukumaran** [comment]
What version of Python are you running?

-- jeet

On 5/8/16 9:33 PM, Lily-WL wrote:
> *python -c "from dendropy.utility.container import FrozenOrderedDict; q
> = FrozenOrderedDict()"*

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------

**Comment by Lily-WL** [comment]
I am using  DendroPy-4.0.3 now.

**Comment by jeetsukumaran** [comment]
I mean Python. I see it is 2.7. But what is its minor version.

Also, why are you using DendroPy 4.0.3?

**Comment by Lily-WL** [comment]
The version of **Python is 2.7**. Maybe meaning the 2.7.0, but "0" is omitted.

Previously I installed DendroPy-4.0.1 through pip installation. Later, because I want to execute "python setup.py test", I downloaded the 4.0.3 version and reinstalled.

**Comment by jeetsukumaran** [comment]
I don't think the issues you are facing having to do with the DendroPy 
version, but there have been lots of fixes and improvements since 4.0.3, 
and, just to be sure we are on the same page, maybe you should upgrade 
to the latest DendroPy.

     $ pip install --upgrade DendroPy

Is there any way you can try this in a new version of Python? The 
current version is 2.7.11. If you are indeed running 2.7.0, then that's 
a LOT of fixes. I am running 2.7.10, and cannot reproduce this error.

On 5/8/16 10:52 PM, Lily-WL wrote:
> The version of *Python is 2.7*. Maybe meaning the 2.7.0, but "0" is omitted.
>
> Previously I installed DendroPy-4.0.1 through pip installation. Later,
> because I want to execute "python setup.py test", I downloaded the 4.0.3
> version and reinstalled.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jeetsukumaran/DendroPy/issues/50#issuecomment-217766147>
>

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------

**Comment by Lily-WL** [comment]
Dear Sir,

Seems the error was gone after installation of Python2.7.10 and DendroPy-4.0.3.

Thank you very much for your support.
