### ISSUE TITLE
Documentation for newick output possibly wrong

### ISSUE THREAD

**Issue by hyanwong** [jeetsukumaran/DendroPy#57]
At https://pythonhosted.org/DendroPy/schemas/newick.html (which I presume is generated from the codebase), under reading, it says
- suppress_internal_node_taxa (boolean, default: True) – If False, internal node labels will be instantantiated into Taxon objects. If True, internal node labels will not be instantantiated as strings.
- suppress_leaf_node_taxa (boolean, default: False) – If False, leaf (external) node labels will be instantantiated into Taxon objects. If True, leaff (external) node labels will not be instantantiated as strings.

Should these read "If True, xxx node labels will _not_ be instantantiated into Taxon objects, but be placed as node labels instead". That's what seems to happen anyway.

**Comment by jeetsukumaran** [comment]
Hi @hyanwong,

You are absolutely right, the documentation is incorrect, and your reading is correct.

Will fix soon.

Thanks for pointing it out!

**Comment by mmore500** [comment]
I think the documentation might actually be correct on this one as is? The logic being, **not** suppressing taxa (i.e., kwarg `False`) *should* result in Taxon objects being instantiated. Feel free to re-open if I am mistaken here.

Did fix `leaff` typo though :+1:
