### ISSUE TITLE
Possible bugs setting parent_node, not _parent_node

### ISSUE THREAD

**Issue by hyanwong** [jeetsukumaran/DendroPy#59]
Just looking through the source at https://pythonhosted.org/DendroPy/_modules/dendropy/datamodel/treemodel.html#Tree.ladderize, I see there are 3 instances where .parent_node is assigned (without leading underscore), e.g. in _set_tail_node():

self._head_node.parent_node = node

_set_seed_node:

self._seed_node.parent_node = None

and in from_split_bitmasks():

parent_node = parent_node.parent_node

Perhaps I'm misunderstanding this, but I was wondering if you mean ._parent_node, not .parent_node in at least 2 of these cases?

**Comment by jeetsukumaran** [comment]
``_parent_node`` is the underlying data structure, meant for private 
(within-DendroPy) storage/manipulation.

``parent_node`` is the managed property exposed to client code.

This is a fairly common Python convention/idiom.

https://github.com/jeetsukumaran/DendroPy/blob/development-master/dendropy/datamodel/treemodel.py#L1982-L1999

On 6/22/16 11:38 AM, hyanwong wrote:
> Just looking through the source at
> https://pythonhosted.org/DendroPy/_modules/dendropy/datamodel/treemodel.html#Tree.ladderize,
> I see there are 3 instances where .parent_node is assigned (without
> leading underscore), e.g. in _set_tail_node():
>
> self._head_node.parent_node = node
>
> _set_seed_node:
>
> self._seed_node.parent_node = None
>
> and in from_split_bitmasks():
>
> parent_node = parent_node.parent_node
>
> Perhaps I'm misunderstanding this, but I was wondering if you mean
> ._parent_node, not .parent_node in at least 2 of these cases?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jeetsukumaran/DendroPy/issues/59>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AABmR713HabkXzYOkKTXgNsigOIGhYztks5qOVblgaJpZM4I769I>.
>

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------

**Comment by hyanwong** [comment]
Ah, I was wondering about that. The thing is, I was surprised to see the managed property seemingly inconsistently used within the Dendropy code base. But I guess either works.

**Comment by jeetsukumaran** [comment]
Some of the code pre-dates the transition of ``parent_node`` to a property.
