### ISSUE TITLE
test failure on ubuntu with python 2.7.11+

### ISSUE THREAD

**Issue by mtholder** [jeetsukumaran/DendroPy#74]
This is hard to reproduce. It does not happen for me when I run the test alone, but If I add `self.maxDiff = None` to `test_dataio_nexml_reader_tree_list.py` and run it in the context of the full test suite, I get:

    ======================================================================
    FAIL: test_collection_comments_and_annotations (dendropy.test.test_dataio_nexml_reader_tree_list.NexmlStandardTreeParsingTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/mtholder/Documents/projects/DendroPy/dendropy/test/test_dataio_nexml_reader_tree_list.py", line 61, in test_collection_comments_and_annotations
        expected_metadata)
      File "/home/mtholder/Documents/projects/DendroPy/dendropy/test/support/standard_file_test_trees.py", line 127, in compare_annotations_to_json_metadata_dict
        self.assertEqual(item_annotations_as_dict, expected_metadata)
    AssertionError: {'Merycoidodon_%_$_permeant': 'envyingly247994 wagonload130853 ganglioneuron4665 [truncated]... != {u'$_demivotary_#_monumentlike': '31', u'!_missuggestion_frondivorous_#': 'False [truncated]...
    - {'!_missuggestion_frondivorous_#': False,
    + {u'!_missuggestion_frondivorous_#': 'False',
    ?  +                                  +     +

    -  '$_!_ichthyodorulite_birthplace': [-34.5128, 15.5375],
    +  u'$_!_ichthyodorulite_birthplace': ['-34.5128', '15.5375'],
    ?  +                                   +        +  +       +

    -  '$_demivotary_#_monumentlike': 31,
    +  u'$_demivotary_#_monumentlike': '31',
    ?  +                               +  +

    -  'Merycoidodon_%_$_permeant': 'envyingly247994 wagonload130853 ganglioneuron466526 horismology561695',
    +  u'Merycoidodon_%_$_permeant': 'envyingly247994 wagonload130853 ganglioneuron466526 horismology561695',
    ?  +

    -  'manganiferous_!_temulency_$': -26.8125}
    +  u'manganiferous_!_temulency_$': '-26.8125'}
    ?  +                               +        +

**Comment by unode** [comment]
I'm getting this too on NixOS when adding dendropy. Here the error is perfectly reproducible:

```
======================================================================
FAIL: test_collection_comments_and_annotations (dendropy.test.test_dataio_nexml_reader_tree_list.NexmlStandardTreeParsingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/nix-build-python2.7-DendroPy-4.3.0.drv-0/DendroPy-4.3.0/dendropy/test/test_dataio_nexml_reader_tree_list.py", line 60, in test_collection_comments_and_annotations
    expected_metadata)
  File "/dev/shm/nix-build-python2.7-DendroPy-4.3.0.drv-0/DendroPy-4.3.0/dendropy/test/support/standard_file_test_trees.py", line 127, in compare_annotations_to_json_metadata_dict
    self.assertEqual(item_annotations_as_dict, expected_metadata)
AssertionError: {'Merycoidodon_%_$_permeant': 'envyingly247994 wagonload130853 ganglioneuron4665 [truncated]... != {u'$_demivotary_#_monumentlike': '31', u'!_missuggestion_frondivorous_#': 'False [truncated]...
Diff is 796 characters long. Set self.maxDiff to None to see it.
```
Anything that can be done to prevent this test from failing?
