### ISSUE TITLE
Feature request: suppress_unifurcations() to return number of unifurcations suppressed

### ISSUE THREAD

**Issue by hyanwong** [jeetsukumaran/DendroPy#75]
It would be handy if suppress_unifurcations() when called as a specific function on a tree returned the number of number of unifurcations that have now been suppressed. I presume this isn't terribly difficult.

**Comment by jeetsukumaran** [comment]
While unfortunately not documented, the ``Tree.suppress_unifurcations()`` method already returns a list of the nodes removed during the procedure: https://github.com/jeetsukumaran/DendroPy/blob/master/dendropy/datamodel/treemodel.py#L5116 .

Will calling ``len()`` on this give you what you want?

**Comment by hyanwong** [comment]
That's even better. Thanks. Just needs documenting then.

**Comment by jeetsukumaran** [comment]
Sorry, I just deleted the previous comment (which, for the record, indicates the return value is al ist of removed nodes) because looking at the code in detail makes me unsure what exactly is being return. Shows the importance of documentation! Let me check and get back to you ....

**Comment by jeetsukumaran** [comment]
So it seems it is list of 2-tuples, where in each 2-tuple the first element is the parent of the unifurcation node and the second element the unifurcating node. So ``len()`` on the return value will give you what you want.

Yes, needs documentation and also a test or two ...
