### ISSUE TITLE
Dendropy incorrectly reads terminating unnamed unifurcations

### ISSUE THREAD

**Issue by hyanwong** [jeetsukumaran/DendroPy#76]
A newick string like this `(()A,(B,C));` is read by Dendropy as having tips labelled A,B, & C, not None,B,C. I.e. the terminating unnamed unification `()` before the A is being thrown away. It works fine if there is a comma in there:

`((,)A,(B,C));`

which has tips None,None,B,C

**Comment by jeetsukumaran** [comment]
Thanks for pointing this out. It should be fixed, and the OCD person in me is screaming for it to be fixed, but, to be honest, I cannot see this as a very high priority right now given the extreme corner case. As work around in the mean time, would a simple text pre-processing of your data source, replacing ``()`` with ``(,)`` work?

**Comment by hyanwong** [comment]
Yes, very niche I know! For my use case I don't need it as I've found that I can simply declare a branch length like `((:123.4)A,(B,C));`. So no urgent need to fix on my part.

**Comment by mmore500** [comment]
Able to reproduce this on my end still

```python3
import dendropy

newick_str = "(()A,(B,C));"
tree = dendropy.Tree.get(
     data=newick_str,
     schema="newick",
)
print(tree.as_string("newick"))

newick_str = "((,)A,(B,C));"
tree = dendropy.Tree.get(
     data=newick_str,
     schema="newick",
)
print(tree.as_string("newick"))
```
