### ISSUE TITLE
Documentation formatting

### ISSUE THREAD

**Issue by beroe** [jeetsukumaran/DendroPy#78]
Is the terminal comma in the *Reading and Writing Trees* section of [the documentation](https://pythonhosted.org/DendroPy/primer/trees.html) correct and supposed to be there?

**Comment by jeetsukumaran** [comment]
Could you be more specific? Which part exactly?

**Comment by beroe** [comment]
``` import` dendropy
tree = dendropy.Tree.get(
    path="trees1.nex",
    schema="nexus",
    tree_offset=2,    # <-- this comma
    )
tree.write(
    path="trees1.newick",
    schema="newick",   # <-- this comma
    )
```

**Comment by jeetsukumaran** [comment]
Yes and no. It is not necessary, but neither is it invalid Python syntax. I like to keep it in multi-line calls such as this so as to easily add/remove/rearrange lines without worrying about the comma.

**Comment by beroe** [comment]
OK, thanks for the explanation. That makes sense, though it can be confusing on first exposure.
