### ISSUE TITLE
as_newick_string() changed to _as_newick_string()

### ISSUE THREAD

**Issue by josephryan** [jeetsukumaran/DendroPy#79]
I have some code that broke sometime between Dendropy 3.12.0 and 4.0.3  (latest) because as_newick_string() changed to _as_newick_string().  I assume that the method went from a public method to a private method?  Is that right?  

Here's the code: 
```
#!/usr/bin/env python

import sys
import dendropy
from dendropy import Tree

if len(sys.argv) != 2:
    sys.exit('Usage: %s NEWICKTREEFILE' % sys.argv[0])

file = sys.argv[1]

tree = Tree.get_from_path(file, "newick")
for nd in tree.postorder_internal_node_iter():
    children = nd.child_nodes()
    for child in children:
        print child.as_newick_string()
        # print child._as_newick_string()
```

The current docs say "
```
as_newick_string(**kwargs)
    This returns the Node as a NEWICK statement according to the given formatting rules. 
This should be used for debugging purposes only. For production purposes, use the the
full-fledged ‘as_string()’ method of the object.
```

I'm not really sure how to make this code work with `as_string()`

Can you offer any advice?

**Comment by jeetsukumaran** [comment]
Yes, it did become private. I guess I never created public support for printing individual nodes as newick strings. So you might want to continue to use the internal method if it suits your purposes. Otherwise, it is a bit of PIA: you have to create a new temporary tree with the node as a seed node, and print that:

    for child in nd.child_node_iter():
        temp_tree = Tree(seed_node=child)
        print(temp_tree.as_string("newick"))

Let me know if this works.

**Comment by josephryan** [comment]
Thank you.  This works.  The output is a little different, so I'm going to keep calling the private method (if you have no plans to change it).

**Comment by jeetsukumaran** [comment]
I don't have plans to change it ... but the main reason I made it a private method was exactly to have the freedom to change it without warning or notice. As I use it for debugging, I wanted to be able to customize the output for my debugging needs. 

The public "as_string()" method takes a whole bunch of keyword arguments that lets you customize the output in any way you want. I would suggest using this for long-term stability.  Failing that, maybe just copy the private function from the library and monkey-patch your object with it under a different name (e.g. "custom_as_newick()"). That should preserve the snapshot of the current method for your needs. 

But again: no plans immediate or forseeable future to change the private function, but that's not a promise/guarantee!
