### ISSUE TITLE
Dedropy mistakenly looking for DNA alphabet in ProteinCharacterMatrix.get

### ISSUE THREAD

**Issue by tauanajc** [jeetsukumaran/DendroPy#81]
When using:
dendropy.**Protein**CharacterMatrix.get(path="file.nex", schema="nexus")
Dendrophy returns an error about DNA alphabet:
Error parsing data source 'file.nex' on line 7 at column 14: Unrecognized character state symbol for state alphabet **'DNA' (DnaStateAlphabet)** : 'L'

I haven't been able to find a way around this.

**Comment by jeetsukumaran** [comment]
As might be inferred from the error, it is finding the letter "L" in the sequence data and is not happy about it because L is not a DNA alphabet. Without the data file, that's all that can be said right now.

**Comment by mmore500** [comment]
Closing this for now, but if more information can be provided happy to re-open. :+1:
