### ISSUE TITLE
functions extract_tree_with_taxa and extract_tree_with_taxa_labels have extra parameters in the documentation

### ISSUE THREAD

**Issue by idavydov** [jeetsukumaran/DendroPy#86]
In the documentation, `extract_tree_with_taxa` and `extract_tree_with_taxa_labels` have parameters `is_apply_filter_to_leaf_nodes` and `is_apply_filter_to_internal_nodes`. In reality there are no such parameters, if you are trying to call:
```
subtree = t.extract_tree_with_taxa_labels([...], is_apply_filter_to_leaf_nodes=True)
```
you get:
```
TypeError: extract_tree_with_taxa_labels() got an unexpected keyword argument 'is_apply_filter_to_leaf_nodes'
```

I am not sure if the error is in the documentation or the function. :)

**Comment by mmore500** [comment]
Thanks for the report! I've fixed the documentation, it is on the version 5 release branch :+1:
