### ISSUE TITLE
Error in CharacterDataSequence.annotations_at when loading Phenoscape Ontotrace NeXML file

### ISSUE THREAD

**Issue by gaurav** [jeetsukumaran/DendroPy#87]
I've found a case where the [`CharacterDataSequence.annotations_at` method](https://pythonhosted.org/DendroPy/library/charmatrixmodel.html#dendropy.datamodel.charmatrixmodel.CharacterDataSequence.annotations_at) crashes. I've included a test Python script and an example NeXML file on which it crashes. On my computer (Windows 10), it gives me the following error:

```
nexml2jsonld master % $ python --version
Python 3.6.1
nexml2jsonld master % $ python .\column_annotations.py
DendroPy: 4.2.0
Taxon: 'Xenurobrycon macropus'
 - taxonID: http://purl.obolibrary.org/obo/VTO_0065870
1
Traceback (most recent call last):
  File ".\column_annotations.py", line 51, in <module>
    print(char_matrix[taxon].annotations_at(count))
  File "C:\Users\Gaurav\scoop\apps\python\current\lib\site-packages\dendropy\datamodel\charmatrixmodel.py", line 362, in annotations_at
    self._character_annotations[idx] = basemodel.AnnotationSet()
TypeError: __init__() missing 1 required positional argument: 'target'
```

The larger question here is how to access character annotations. For example, given the following char description:
```
<char id="UBERON_0010527" label="cavity of bone organ" about="#UBERON_0010527" states="sbaa1df0d-ee55-4eee-bb60-617520728203">
  <meta xsi:type="ResourceMeta" rel="obo:IAO_0000219" href="http://purl.obolibrary.org/obo/UBERON_0010527" />
</char>
```
I'd like to know that this character [denotes](http://purl.obolibrary.org/obo/IAO_0000219) [cavity of bone organ](http://purl.obolibrary.org/obo/UBERON_0010527). These [kinds of file](https://github.com/jeetsukumaran/DendroPy/files/1555906/column_annotations.zip) are produced by Phenoscape's [Ontotrace tool](http://kb.phenoscape.org/#/ontotrace); you can see the example file I've uploaded [on Github](https://github.com/cboettig/nexld/blob/master/inst/extdata/ontotrace.xml). Is there any way of accessing that data from DendroPy?

**Comment by jeetsukumaran** [comment]
Yep, this is a bug. A double bug in fact. Thanks for finding it and reporting it. Fixed in the `development-master` current HEAD, 5ae4800 .

You can access this information using:

    for char_type in char_matrix.character_types:
        for annote in char_type.annotations:
            print(" - {}: {}".format(annote.name, annote.value))

    for taxon, seq in char_matrix.items():
        for cell, char_type, cell_annote in seq.cell_iter():
            for annote in char_type.annotations:
                print(" - {}: {}".format(annote.name, annote.value))

Let me know if this works ... or if I have ended breaking something else :)

**Comment by gaurav** [comment]
That works! Thanks so much, Jeet!
