### ISSUE TITLE
random seed reproducibility of treesim.birth_death_tree when using numpy.save

### ISSUE THREAD

**Issue by idavydov** [jeetsukumaran/DendroPy#88]
Hi, I've discovered an obscure issue.

`birth_death_tree` results are changing if `numpy.save` was used in the code.

You need two mostly identical files `1.py` and `2.py`:

```python
# 1.py
import random

import numpy as np

import dendropy
from dendropy.simulate import treesim

np.save('file', 'aaa')

rng=random.Random(1)

t = treesim.birth_death_tree(
    birth_rate=10.,
    death_rate=5.,
    birth_rate_sd=0.5,
    death_rate_sd=0.5,
    num_extant_tips=10,
    rng=rng)
print(t)
# this last line only needed in 2.py
print('bye')
```

Now two scripts produce slightly different results:

```bash
$ diff 1.py 2.py
20a21
> print('bye')
$ python 1.py 
(((T5:0.161869436373317,T3:0.16186943637331702):0.023498203571967177,(T2:0.06328384937399689,((T7:0.0033653976337396055,(T10:0.0,T8:0.0):0.0033653976337396055):0.02687413460381695,T6:0.030239532237556554):0.033044317136440335):0.12208379057128729):0.11452667890031788,((T9:0.012543727576614564,T1:0.012543727576614564):0.034777908390860215,T4:0.04732163596747478):0.2525726828781273):0.1867278924742215
$ python 2.py 
(((T10:0.05117261119826575,(((T5:0.0,T8:0.0):0.01079898660762326,T9:0.01079898660762326):0.02286191361221651,T7:0.03366090021983977):0.017511710978425975):0.2613333470907571,(T2:0.003592458452326968,T6:0.003592458452326968):0.30891349983669586):0.017361623925104708,((T3:0.10902504017366038,T1:0.10902504017366038):0.2026460498516629,T4:0.31167109002532334):0.01819649218880426):0.10581733263041147

```

You can clone files from [here](https://gist.github.com/idavydov/57c11d78224efa15916e601dbbf6a734).

Behaviour is slightly different between python2 and python3. In python2, `2.py` generates different results every run, while `1.py` is returning the same tree. In python3 both are reproducible, but inconsistent with each other.

This was done in a clean virtualenv environment with dendropy 4.3.0 and numpy from pypi 1.13.3. I tried two different linux machines. The bug reproduces on both.

In dendropy 4.2.0 I could not reproduce the issue.

**Comment by mmore500** [comment]
Confirmed this has been fixed in newer versions of DendroPy.
