### ISSUE TITLE
Documentation for GenBank generate_char_matrix inconsistent with code

### ISSUE THREAD

**Issue by tiagoantao** [jeetsukumaran/DendroPy#91]
`generate_char_matrix` has a method called `gb_to_taxon_fn` but the documentation at https://pythonhosted.org/DendroPy/primer/genbank.html calls it `gb_to_taxon_func`.

Incidentally, in previous versions the name was `gb_to_taxon_func`.

One of them should be changed, I think (doc or src)

**Comment by jeetsukumaran** [comment]
Fixed in latest revision.
