### ISSUE TITLE
extract_tree_with_taxa + str() produces malformed tree

### ISSUE THREAD

**Issue by niemasd** [jeetsukumaran/DendroPy#95]
I am using the following Newick-format tree: [merged_tree_0.tre.gz](https://github.com/jeetsukumaran/DendroPy/files/1993497/merged_tree_0.tre.gz)

This is my script:

```python
from dendropy import Tree
def label(u):
    return str(u.taxon).replace("'",'')
tree = Tree.get(data=gzip.open('merged_tree_0.tre.gz').read().decode(),schema='newick')
taxa = [leaf.taxon for leaf in tree.leaf_node_iter() if -1 < float(label(leaf).split('|')[-1]) < 9]
print((str(tree.extract_tree_with_taxa(taxa))))
```

However, the resulting tree is malformed (it's missing a semicolon). I tried with `suppress_unifurcations` off and it had the same result.

I also tried implementing my own version in which, for each taxon *t*, I mark *t* and all ancestors of *t* as "keep", and I perform a BFS starting at the seed node: if the current node is marked "keep", add all of its children to the BFS queue; if not, delete it from its parent's children via the `remove_child` function. This code *also* had the same outcome (malformed output tree missing a semicolon). I'm guessing perhaps there's a more fundamental issue with deleting nodes, and it's happening to trigger this issue in `extract_tree_with_taxa` due to internal node deletion

**Comment by niemasd** [comment]
Also, I wrote my own version of the `extract_tree_with_taxa` function that seems to be much faster than the original, in case anyone is interested in using it

```python
def extract_tree_with_taxa(tree, taxa, suppress_unifurcations=True):
    taxon_to_leaf = {}
    for n in tree.preorder_node_iter():
        n.keep = False
        if n.is_leaf():
            taxon_to_leaf[n.taxon] = n
    for t in taxa:
        for n in taxon_to_leaf[t].ancestor_iter(inclusive=True):
            n.keep = True
    out = Tree()
    q_old = Queue(); q_old.put(tree.seed_node)
    q_new = Queue(); q_new.put(out.seed_node)
    while not q_old.empty():
        n_old = q_old.get(); n_new = q_new.get()
        for c_old in n_old.child_node_iter():
            if c_old.keep:
                c_new = Node(taxon=c_old.taxon, label=c_old.label, edge_length=c_old.edge_length); n_new.add_child(c_new)
                q_old.put(c_old); q_new.put(c_new)
    if suppress_unifurcations:
        out.suppress_unifurcations()
    return out
```

**Comment by mmore500** [comment]
`__str__` 

https://github.com/jeetsukumaran/DendroPy/blob/c31c1d986b0e6d72aa90e4fef61707e055ce3779/src/dendropy/datamodel/treemodel/_tree.py#L3947

appears to delegate to a quick and dirty internal debugging print 

<https://github.com/jeetsukumaran/DendroPy/blob/c31c1d986b0e6d72aa90e4fef61707e055ce3779/src/dendropy/datamodel/treemodel/_tree.py#L4274>

As a potential public-facing endpoint, `__str__` method should probably be updated to delegate to the proper `as_string("Newick")` instead.

**Comment by niemasd** [comment]
I've since written my own tree Python package ([TreeSwift](https://github.com/niemasd/TreeSwift)) with this functionality implemented if it's of interest 😄 

https://niema.net/TreeSwift/#treeswift.Tree.extract_tree_with

**Comment by mmore500** [comment]
This has been fixed for DendroPy 5.
