### ISSUE TITLE
documentation: viewing and displaying Newick tree needs semi-colon

### ISSUE THREAD

**Issue by thekswenson** [jeetsukumaran/DendroPy#97]
The example in the section "Viewing and Displaying Trees" (https://dendropy.org/primer/trees.html#viewing-and-displaying-trees) needs a semi-colon in the Newick string format.

As is, a cryptic error message is given by python:

"UnexpectedEndOfStreamError: Error parsing data source on line 1 at column 2: Unexpected end of stream"

**Comment by jeetsukumaran** [comment]
Thanks. Fixed in 0d96c964
